In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

from get_data import get_data, load_data

In [2]:

data = get_data()
data

,lat,lon,distance,arclength,speed,abs_speed
datetimes,,,,,,
2014-09-01 16:01:00,40.6530,-73.8000,NaN,NaN,NaN,NaN
2014-09-01 17:01:00,40.7530,-73.9966,18079.982480,18079.988547,5.022219,5.022219
2014-09-01 17:30:00,41.7686,-73.9556,112968.098622,112969.578604,64.925045,64.925045
2014-09-01 18:06:00,42.7512,-74.0065,109325.062566,109326.403932,50.614076,50.614076
2014-09-01 18:36:00,44.7960,-73.6729,228802.058237,228814.355724,127.119087,127.119087
2014-09-01 18:56:23,43.7963,-74.0064,114136.653629,114138.180016,93.326394,93.326394
2014-09-01 19:06:00,44.6880,-75.1830,134765.773416,134768.286079,233.567220,233.567220
2014-09-01 19:46:00,44.7702,-76.8646,131904.290868,131906.646847,54.961103,54.961103
2014-09-01 20:07:00,44.7402,-77.9949,88552.636807,88553.349639,70.280436,70.280436
2014-09-01 22:07:00,47.7402,-76.9949,343066.252459,343107.714364,47.653849,47.653849
2014-09-01 23:07:00,45.7402,-73.9949,329274.909200,329311.568149,91.475436,91.475436
2014-09-01 23:50:00,49.7402,-71.9949,474105.478961,474214.942422,183.804241,183.804241
2014-09-02 16:01:00,50.6530,-73.8000,184594.422023,184600.879610,3.168570,3.168570
2014-09-02 17:01:00,50.7530,-73.9966,20244.682091,20244.690609,5.623525,5.623525
2014-09-02 17:30:00,51.7686,-73.9556,112984.056335,112985.536944,64.934217,64.934217
2014-09-02 18:06:00,52.7512,-74.0065,109350.421029,109351.763328,50.625816,50.625816
2014-09-02 18:36:00,54.7960,-73.6729,229319.107579,229331.488633,127.406383,127.406383
2014-09-02 18:56:23,53.7963,-74.0064,115166.373184,115167.941258,94.168390,94.168390
2014-09-02 19:06:00,54.6880,-75.1830,145263.615015,145266.761818,251.762152,251.762152
2014-09-02 19:46:00,54.7702,-76.8646,152928.515303,152932.187002,63.721745,63.721745
2014-09-02 20:07:00,54.7402,-77.9949,102697.576847,102698.688750,81.506896,81.506896
2014-09-02 22:07:00,57.7402,-76.9949,346107.939781,346150.514566,48.076460,48.076460
2014-09-02 23:07:00,55.7402,-73.9949,356663.245858,356709.836832,99.086066,99.086066
2014-09-02 23:50:00,59.7402,-71.9949,482754.350283,482869.917009,187.158883,187.158883
2014-09-03 06:01:00,60.6530,-73.8000,201573.721869,201582.130479,9.055801,9.055801
2014-09-03 07:01:00,60.7530,-73.9966,22070.544296,22070.555333,6.130710,6.130710
2014-09-03 07:30:00,61.7686,-73.9556,112998.809318,113000.290507,64.942696,64.942696
2014-09-03 08:06:00,62.7512,-74.0065,109373.559454,109374.902605,50.636529,50.636529
2014-09-03 08:36:00,64.7960,-73.6729,229780.559596,229793.015549,127.662786,127.662786
2014-09-03 08:56:23,63.7963,-74.0064,116073.121017,116074.726422,94.909834,94.909834
2014-09-03 09:06:00,64.6880,-75.1830,153993.357271,153997.106207,266.892732,266.892732
2014-09-03 09:46:00,64.7702,-76.8646,169331.535097,169336.519597,70.556883,70.556883
2014-09-03 16:01:00,70.6530,-73.8000,725678.893217,726071.756707,32.269856,32.269856
2014-09-03 17:01:00,70.7530,-73.9966,23438.263036,23438.276253,6.510632,6.510632
2014-09-03 17:30:00,71.7686,-73.9556,113010.578931,113012.060583,64.949460,64.949460
2014-09-03 18:06:00,72.7512,-74.0065,109391.689207,109393.033027,50.644923,50.644923
2014-09-03 18:36:00,74.7960,-73.6729,230131.238037,230143.751112,127.857640,127.857640
2014-09-03 18:56:23,73.7963,-74.0064,116751.502872,116753.136592,95.464543,95.464543
2014-09-03 19:06:00,74.6880,-75.1830,160262.359985,160266.585688,277.758381,277.758381
2014-09-03 19:46:00,74.7702,-76.8646,180608.088722,180614.136898,75.255890,75.255890
2014-09-03 20:07:00,74.7402,-77.9949,121304.873911,121306.706336,96.275164,96.275164
2014-09-03 22:07:00,77.7402,-76.9949,350584.418572,350628.667155,48.698426,48.698426
2014-09-03 23:07:00,75.7402,-73.9949,393470.171666,393532.731475,109.314648,109.314648
2014-09-03 23:50:00,79.7402,-71.9949,494884.661119,495009.164313,191.864017,191.864017

In [3]:
# data = data.rename(columns={'datetimes':'index'}).set_index('index')
data.speed * (1 / data.speed.max())

datetimes
2014-09-01 16:01:00         NaN
2014-09-01 17:01:00    0.018081
2014-09-01 17:30:00    0.233746
2014-09-01 18:06:00    0.182223
2014-09-01 18:36:00    0.457661
2014-09-01 18:56:23    0.335998
2014-09-01 19:06:00    0.840901
2014-09-01 19:46:00    0.197874
2014-09-01 20:07:00    0.253027
2014-09-01 22:07:00    0.171566
2014-09-01 23:07:00    0.329335
2014-09-01 23:50:00    0.661741
2014-09-02 16:01:00    0.011408
2014-09-02 17:01:00    0.020246
2014-09-02 17:30:00    0.233780
2014-09-02 18:06:00    0.182266
2014-09-02 18:36:00    0.458695
2014-09-02 18:56:23    0.339030
2014-09-02 19:06:00    0.906407
2014-09-02 19:46:00    0.229414
2014-09-02 20:07:00    0.293445
2014-09-02 22:07:00    0.173087
2014-09-02 23:07:00    0.356735
2014-09-02 23:50:00    0.673819
2014-09-03 06:01:00    0.032603
2014-09-03 07:01:00    0.022072
2014-09-03 07:30:00    0.233810
2014-09-03 08:06:00    0.182304
2014-09-03 08:36:00    0.459618
2014-09-03 08:56:23    0.341699
2014-09-03 09:06:00    0.960881
2014-09-03 09:46:00    0.254023
2014-09-03 16:01:00    0.116180
2014-09-03 17:01:00    0.023440
2014-09-03 17:30:00    0.233834
2014-09-03 18:06:00    0.182334
2014-09-03 18:36:00    0.460320
2014-09-03 18:56:23    0.343696
2014-09-03 19:06:00    1.000000
2014-09-03 19:46:00    0.270940
2014-09-03 20:07:00    0.346615
2014-09-03 22:07:00    0.175327
2014-09-03 23:07:00    0.393560
2014-09-03 23:50:00    0.690759
Name: speed, dtype: float64

In [38]:
data.reset_index(level=0)[["datetimes", "speed", "lat", "lon"]]

             datetimes       speed      lat      lon
0  2014-09-01 16:01:00         NaN  40.6530 -73.8000
1  2014-09-01 17:01:00    5.022219  40.7530 -73.9966
2  2014-09-01 17:30:00   64.925045  41.7686 -73.9556
3  2014-09-01 18:06:00   50.614076  42.7512 -74.0065
4  2014-09-01 18:36:00  127.119087  44.7960 -73.6729
5  2014-09-01 18:56:23   93.326394  43.7963 -74.0064
6  2014-09-01 19:06:00  233.567220  44.6880 -75.1830
7  2014-09-01 19:46:00   54.961103  44.7702 -76.8646
8  2014-09-01 20:07:00   70.280436  44.7402 -77.9949
9  2014-09-01 22:07:00   47.653849  47.7402 -76.9949
10 2014-09-01 23:07:00   91.475436  45.7402 -73.9949
11 2014-09-01 23:50:00  183.804241  49.7402 -71.9949
12 2014-09-02 16:01:00    3.168570  50.6530 -73.8000
13 2014-09-02 17:01:00    5.623525  50.7530 -73.9966
14 2014-09-02 17:30:00   64.934217  51.7686 -73.9556
15 2014-09-02 18:06:00   50.625816  52.7512 -74.0065
16 2014-09-02 18:36:00  127.406383  54.7960 -73.6729
17 2014-09-02 18:56:23   94.168390  53.7963 -74.0064
18 2014-09-02 19:06:00  251.762152  54.6880 -75.1830
19 2014-09-02 19:46:00   63.721745  54.7702 -76.8646
20 2014-09-02 20:07:00   81.506896  54.7402 -77.9949
21 2014-09-02 22:07:00   48.076460  57.7402 -76.9949
22 2014-09-02 23:07:00   99.086066  55.7402 -73.9949
23 2014-09-02 23:50:00  187.158883  59.7402 -71.9949
24 2014-09-03 06:01:00    9.055801  60.6530 -73.8000
25 2014-09-03 07:01:00    6.130710  60.7530 -73.9966
26 2014-09-03 07:30:00   64.942696  61.7686 -73.9556
27 2014-09-03 08:06:00   50.636529  62.7512 -74.0065
28 2014-09-03 08:36:00  127.662786  64.7960 -73.6729
29 2014-09-03 08:56:23   94.909834  63.7963 -74.0064
30 2014-09-03 09:06:00  266.892732  64.6880 -75.1830
31 2014-09-03 09:46:00   70.556883  64.7702 -76.8646
32 2014-09-03 16:01:00   32.269856  70.6530 -73.8000
33 2014-09-03 17:01:00    6.510632  70.7530 -73.9966
34 2014-09-03 17:30:00   64.949460  71.7686 -73.9556
35 2014-09-03 18:06:00   50.644923  72.7512 -74.0065
36 2014-09-03 18:36:00  127.857640  74.7960 -73.6729
37 2014-09-03 18:56:23   95.464543  73.7963 -74.0064
38 2014-09-03 19:06:00  277.758381  74.6880 -75.1830
39 2014-09-03 19:46:00   75.255890  74.7702 -76.8646
40 2014-09-03 20:07:00   96.275164  74.7402 -77.9949
41 2014-09-03 22:07:00   48.698426  77.7402 -76.9949
42 2014-09-03 23:07:00  109.314648  75.7402 -73.9949
43 2014-09-03 23:50:00  191.864017  79.7402 -71.9949

In [36]:
[point for point in data[["speed", "lat", "lon"]].values]

[array([    nan,  40.653, -73.8  ]),
 array([  5.02221904,  40.753     , -73.9966    ]),
 array([ 64.92504517,  41.7686    , -73.9556    ]),
 array([ 50.61407589,  42.7512    , -74.0065    ]),
 array([127.11908651,  44.796     , -73.6729    ]),
 array([ 93.32639413,  43.7963    , -74.0064    ]),
 array([233.56722024,  44.688     , -75.183     ]),
 array([ 54.96110285,  44.7702    , -76.8646    ]),
 array([ 70.28043622,  44.7402    , -77.9949    ]),
 array([ 47.65384922,  47.7402    , -76.9949    ]),
 array([ 91.4754356,  45.7402   , -73.9949   ]),
 array([183.80424125,  49.7402    , -71.9949    ]),
 array([  3.16856985,  50.653     , -73.8       ]),
 array([  5.62352517,  50.753     , -73.9966    ]),
 array([ 64.93421663,  51.7686    , -73.9556    ]),
 array([ 50.62581636,  52.7512    , -74.0065    ]),
 array([127.40638257,  54.796     , -73.6729    ]),
 array([ 94.16839024,  53.7963    , -74.0064    ]),
 array([251.7621522,  54.688    , -75.183    ]),
 array([ 63.72174458,  54.7702    , -76.8646    ]),
 array([ 81.50689583,  54.7402    , -77.9949    ]),
 array([ 48.07646036,  57.7402    , -76.9949    ]),
 array([ 99.08606579,  55.7402    , -73.9949    ]),
 array([187.15888256,  59.7402    , -71.9949    ]),
 array([  9.05580101,  60.653     , -73.8       ]),
 array([  6.13070981,  60.753     , -73.9966    ]),
 array([ 64.94269569,  61.7686    , -73.9556    ]),
 array([ 50.63652898,  62.7512    , -74.0065    ]),
 array([127.66278642,  64.796     , -73.6729    ]),
 array([ 94.90983354,  63.7963    , -74.0064    ]),
 array([266.89273173,  64.688     , -75.183     ]),
 array([ 70.55688317,  64.7702    , -76.8646    ]),
 array([ 32.26985585,  70.653     , -73.8       ]),
 array([  6.51063229,  70.753     , -73.9966    ]),
 array([ 64.94946011,  71.7686    , -73.9556    ]),
 array([ 50.6449227,  72.7512   , -74.0065   ]),
 array([127.85763951,  74.796     , -73.6729    ]),
 array([ 95.46454341,  73.7963    , -74.0064    ]),
 array([277.75838074,  74.688     , -75.183     ]),
 array([ 75.25589037,  74.7702    , -76.8646    ]),
 array([ 96.27516376,  74.7402    , -77.9949    ]),
 array([ 48.69842599,  77.7402    , -76.9949    ]),
 array([109.31464763,  75.7402    , -73.9949    ]),
 array([191.86401718,  79.7402    , -71.9949    ])]

In [24]:
[f"datetimes : {point[0]} lat : {point[1]} lon : {point[2]} speed : {point[3]}" for point in data.reset_index(level=0)[["datetimes", "speed", "lat", "lon"]]]

['speed : nan lat : 40.653 lon, : -73.8',
 'speed : 5.022219040778319 lat : 40.753 lon, : -73.9966',
 'speed : 64.9250451744533 lat : 41.7686 lon, : -73.9556',
 'speed : 50.614075894236244 lat : 42.7512 lon, : -74.0065',
 'speed : 127.11908651305943 lat : 44.796 lon, : -73.6729',
 'speed : 93.32639412557164 lat : 43.7963 lon, : -74.0064',
 'speed : 233.56722024065976 lat : 44.688 lon, : -75.183',
 'speed : 54.96110285277124 lat : 44.7702 lon, : -76.8646',
 'speed : 70.28043622138176 lat : 44.7402 lon, : -77.9949',
 'speed : 47.65384921720629 lat : 47.7402 lon, : -76.9949',
 'speed : 91.47543559697371 lat : 45.7402 lon, : -73.9949',
 'speed : 183.80424124870297 lat : 49.7402 lon, : -71.9949',
 'speed : 3.16856985256444 lat : 50.653 lon, : -73.8',
 'speed : 5.623525169033794 lat : 50.753 lon, : -73.9966',
 'speed : 64.93421663437637 lat : 51.7686 lon, : -73.9556',
 'speed : 50.62581635557056 lat : 52.7512 lon, : -74.0065',
 'speed : 127.40638257364556 lat : 54.796 lon, : -73.6729',
 'speed : 94.16839023541513 lat : 53.7963 lon, : -74.0064',
 'speed : 251.76215219718185 lat : 54.688 lon, : -75.183',
 'speed : 63.72174458416174 lat : 54.7702 lon, : -76.8646',
 'speed : 81.50689583352742 lat : 54.7402 lon, : -77.9949',
 'speed : 48.076460356423055 lat : 57.7402 lon, : -76.9949',
 'speed : 99.0860657867068 lat : 55.7402 lon, : -73.9949',
 'speed : 187.1588825618117 lat : 59.7402 lon, : -71.9949',
 'speed : 9.055801009855662 lat : 60.653 lon, : -73.8',
 'speed : 6.130709814614139 lat : 60.753 lon, : -73.9966',
 'speed : 64.94269569390141 lat : 61.7686 lon, : -73.9556',
 'speed : 50.63652898391592 lat : 62.7512 lon, : -74.0065',
 'speed : 127.66278641592488 lat : 64.796 lon, : -73.6729',
 'speed : 94.90983354215712 lat : 63.7963 lon, : -74.0064',
 'speed : 266.89273172845736 lat : 64.688 lon, : -75.183',
 'speed : 70.55688316545178 lat : 64.7702 lon, : -76.8646',
 'speed : 32.26985585363768 lat : 70.653 lon, : -73.8',
 'speed : 6.510632292520105 lat : 70.753 lon, : -73.9966',
 'speed : 64.94946010545316 lat : 71.7686 lon, : -73.9556',
 'speed : 50.64492269753264 lat : 72.7512 lon, : -74.0065',
 'speed : 127.85763950652942 lat : 74.796 lon, : -73.6729',
 'speed : 95.46454341092338 lat : 73.7963 lon, : -74.0064',
 'speed : 277.7583807426107 lat : 74.688 lon, : -75.183',
 'speed : 75.25589037416515 lat : 74.7702 lon, : -76.8646',
 'speed : 96.27516375844044 lat : 74.7402 lon, : -77.9949',
 'speed : 48.698425993713215 lat : 77.7402 lon, : -76.9949',
 'speed : 109.31464763187401 lat : 75.7402 lon, : -73.9949',
 'speed : 191.86401717550353 lat : 79.7402 lon, : -71.9949']

In [4]:
new_line = "2014-09-01 17:01:00,40.753,-73.9966"

DATA_URL = ('https://drive.google.com/file/d/1ZCq_5CMvtDyYihhIARnllRXVNEDSed70/view?usp=sharing')

df2 = data.loc[[10]]
df2.to_csv(DATA_URL, mode="a")

# with open(DATA_URL,'a') as f:
#         f.write(new_line)

KeyError: "None of [Int64Index([10], dtype='int64', name='datetimes')] are in the [index]"